development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: radmad_dev_db
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: radmad_test_db
  pool: 5
  username: radmad_test_db
  password: radmad_test_db
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: radmad_prod_db
  pool: 5
  username: radmad_prod_db
  password: radmad_prod_db
  host: localhost
